### ISSUE TITLE
시연 전 구현할 것들 정리

### ISSUE THREAD

**Issue by return0927** [return0927/coffeebean-front#20]
### 프론트엔드
- [x] 소비자 주문내역 확인
- [x] 소비자 상품 주문하기
- [x] 판매자 상품 목록 조회하기
- [x] 판매자 상품 등록하기
- [x] ~~판매자 상품 삭제하기~~ 구현 안 함
- [x] 필터링 검색하기

### 백엔드
- [x] 소비자 주문내역 확인 (`GET /api/orders/`)
- [x] 소비자 상품 주문하기 (`POST /api/orders/`)
- [x] 판매자 상품 목록 조회하기 (`GET /api/products/my`)
- [x] 판매자 상품 등록하기 (`POST /api/products/`)
- [x] 판매자 상품 수정하기 (`PUT /api/products/{id}`)
- [x] ~~판매자 상품 삭제하기~~ 구현 안 함
- [x] 필터링 검색하기

**Comment by bumjuni** [comment]
- [x] 판매자 로그인 시 frontBar에서 마이페이지>주문내역 대신 대시보드 리다이렉트
